train_dir: "/work/c-2iia/sp165339/UNet_Liver_Segmentation_2D/2D_Data_128/train"
val_dir: "/work/c-2iia/sp165339/UNet_Liver_Segmentation_2D/2D_Data_128/val"

# train_dir: "C:/Users/penda/Documents/Study Materials/Machine and Deep Learning/Project/2D_Data_128_new/train"
# val_dir: "C:/Users/penda/Documents/Study Materials/Machine and Deep Learning/Project/2D_Data_128_new/val"

n_classes: 3
img_channels: 1
